[package]
name = "voting-machine-core"
version = "0.12.0"
edition = "2021"

[dependencies]
risc0-zkp = { git = "https://github.com/risc0/risc0.git", rev = "8a5151f19aa405e1fcac04acda23042367df3a0a", default-features = false }
serde = { version = "1.0", default-features = false }
