[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "d02f606ab7d59ad45dc75314eb3e0eef5c9a26b7" }

[package.metadata.risc0]
methods = ["guest"]
