[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "eaaae8b0dbba8658a62985d5d4b209de5ec6817d" }

[package.metadata.risc0]
methods = ["guest"]
