[package]
name = "json-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { git = "https://github.com/risc0/risc0.git", rev = "65fb3871e3ef468be0a306d9f1adf5631d943b46", default-features = false }
serde = "1.0"
